# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")

setup(
    long_description=readme,
    name="qiskit-rigetti",
    version="0.4.4",
    description="Provider for running Qiskit circuits on Rigetti QPUs and simulators.",
    python_requires="==3.*,>=3.7.0",
    project_urls={
        "documentation": "https://qiskit-rigetti.readthedocs.io",
        "repository": "https://github.com/rigetti/qiskit-rigetti",
    },
    author="Rigetti Computing",
    license="Apache-2.0",
    keywords="Qiskit Quil Rigetti pyQuil Quantum",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "Programming Language :: Other",
        "Topic :: Scientific/Engineering :: Physics",
        "Typing :: Typed",
    ],
    packages=[
        "node_modules.npm.node_modules.node-gyp.gyp.pylib.gyp",
        "node_modules.npm.node_modules.node-gyp.gyp.pylib.gyp.generator",
        "qiskit_rigetti",
        "qiskit_rigetti.gates",
        "qiskit_rigetti.hooks",
    ],
    package_dir={"": "."},
    package_data={"qiskit_rigetti": ["*.typed"]},
    install_requires=[
        'importlib-metadata; python_version < "3.8"',
        "numpy==1.*,>=1.20.1",
        "pyquil==3.*,>=3.0.0",
        "qiskit==0.*,>=0.27.0",
    ],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1",
            "flake8==3.*,>=3.8.1",
            "mypy==0.*,>=0.800.0",
            "pip-licenses==3.*,>=3.5.1",
            "pytest==6.*,>=6.2.2",
            "pytest-cov==2.*,>=2.11.1",
            "pytest-httpx==0.*,>=0.9.0",
            "pytest-mock==3.*,>=3.6.1",
        ],
        "docs": [
            "furo==2021.*,>=2021.7.5.b38",
            "ipython==7.*,>=7.25.0",
            "myst-parser==0.*,>=0.15.1",
            "nbsphinx==0.*,>=0.8.6",
            "sphinx==4.*,>=4.1.1",
            "sphinx-autoapi==1.*,>=1.8.1",
            "sphinx-autobuild==2021.*,>=2021.3.14",
        ],
    },
)
