#!/usr/bin/env bash

curl -sSL https://install.python-poetry.org | python
. $HOME/.poetry/env
poetry --version
poetry config virtualenvs.in-project true
poetry run python -m ensurepip --upgrade
poetry update
poetry install -vv $1
